In [1]:
import numpy as np
x = np.array([[1,2],[3,4],[5,6]])
# this concept is known as advance indexing or fancy indexing
y = x[[0,1,2],[0,1,0]]
print(y)

[1 4 5]


In [4]:
import numpy as np
matrix = np.array([[[[0, 1, 2], [3, 4, 5] ],[[6, 7, 8],[9, 10, 11] ]],[[[12, 13, 14], [15, 16, 17]],
                  [[18, 19, 20],[21, 22, 23] ] ], [[ [24, 25, 26], [27, 28, 29] ], [ [30, 31, 32], [33, 34, 35]]]])

print(matrix.shape)
print(matrix)


(3, 2, 2, 3)
[[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]]


 [[[12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]]]


 [[[24 25 26]
   [27 28 29]]

  [[30 31 32]
   [33 34 35]]]]


In [5]:
import numpy as np
# matrix = np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]])
matrix = np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]])

print(matrix.shape)
print(matrix)

(3, 2, 2, 3)
[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]


In [ ]:
import numpy as np
# Original array
x = np.array([[ 0,  1,  2], [ 3,  4,  5], [ 6,  7,  8],[ 9, 10, 11]])
print("Original array:")
print(x)
# Slicing
z = x[1:4, 1:3]
print("\nAfter slicing, our array becomes:")
print(z)
# Using advanced index for column
y = x[1:4, [1, 2]]
print("\nSlicing using advanced index for column:")
print(y)
# program to print 0,4,8,9
w = x[[0,1,2,3],[0,1,2,0]]
print(w)

Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

After slicing, our array becomes:
[[ 4  5]
 [ 7  8]
 [10 11]]

Slicing using advanced index for column:
[[ 4  5]
 [ 7  8]
 [10 11]]
[0 4 8 9]
