In [ ]:
import numpy as np
a=np.arange(1,11,2)
b=a
print(b)

[1 3 5 7 9]


In [ ]:
import numpy as np
a=np.arange(1,9,2)
b=a+2
print(b)

[3 5 7 9]


In [ ]:
# it prints square root
print(np.sqrt(b))
# it prints exponential means value of exponential is equal to 2.71
print(np.exp(b))

[1.73205081 2.23606798 2.64575131 3.        ]
[  20.08553692  148.4131591  1096.63315843 8103.08392758]


In [ ]:
a=np.arange(1,9,2)
# it prints the data type
print(a.dtype)
arr = np.array([1, 2, 3, 4])
print(arr)
print(arr.dtype)

int64
[1 2 3 4]
int64


In [ ]:
arr = np.array([1.0,2.0])
print(arr)
arr = np.array([1,2.0])
print(arr.dtype)

[1. 2.]
float64


In [ ]:
arr = np.array('hlo')
print(arr.dtype)

<U3


In [ ]:
# data type conversion
arr = np.array([1, 2, 3, 4],dtype='str')
print(arr)
print(arr.dtype)
arr = np.array([1, 2, 3, 4],dtype='float')
print(arr)
print(arr.dtype)

['1' '2' '3' '4']
<U1
[1. 2. 3. 4.]
float64


In [ ]:
# it convert data type of int to float
arr = np.array([1, 2, 3, 4])
new = arr.astype('float')
print(new)
print(new.dtype)
# it convert data type of float to int
arr = np.array([1.0, 2.45, 3.12, 4.99])
ne = arr.astype('int')
print(ne)
print(ne.dtype)


[1. 2. 3. 4.]
float64
[1 2 3 4]
int64


In [ ]:
arr = np.array([1, 0, -3, 4])
new = arr.astype('bool')
print(new)
print(new.dtype)

[ True False  True  True]
bool


In [ ]:
arr = np.array([[1, 2, 3, 4]])
# ndim prints the dimension of array
print(arr.ndim)
# shape prints the shape of array means how many rows and columns
print(arr.shape)

2
(1, 4)


In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr)
print(arr.ndim)
print(arr.shape)
# by using ndmin we can increase the dimension of array
arr = np.array([1, 2, 3, 4],ndmin=4)
print(arr)
print(arr.ndim)
print(arr.shape)

[1 2 3 4]
1
(4,)
[[[[1 2 3 4]]]]
4
(1, 1, 1, 4)
