In [ ]:
import numpy as np
arr = np.array([2,3,4,5,6])
nc = arr
nc[0] = 12
# here all original and copy array are same but by using copy function only copiyed array change
# printing the values
print("Original array : ",arr)
print("assigned array : ",nc)
print(arr.shape)

Original array :  [12  3  4  5  6]
assigned array :  [12  3  4  5  6]
(5,)


In [ ]:
import numpy as np

# joining array using stack function
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2))
print(arr) # Output: [1 2 3 4 5 6]
arr = np.stack((arr1, arr2),axis=1)
print(arr)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
import numpy as np

# joining array using hstack function
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
# hstack function is use to join the array in horizontal direction
print(arr)


[1 2 3 4 5 6]


In [ ]:
import numpy as np

# joining array using vstack function
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
# vstack function is use to join the array in vertical direction
print(arr)


[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
# joining array using stack function
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2))
print(arr) # Output: [1 2 3 4 5 6]
arr = np.stack((arr1, arr2),axis=1)
print(arr)

In [ ]:
import numpy as np

# Example using numpy.append
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2))
# stack function is use to join the array
print(arr) # Output: [1 2 3 4 5 6]
arr = np.stack((arr1, arr2),axis=0)
print(arr)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3])
# append basically adds the elements in array  at last of the array
new_arr = np.append(arr,[4, 5, 6] )
# but here single element add without bracket
new1_arr = np.append(arr,99 )
print(new_arr)  # Output: [1 2 3 4 5 6]
print(new1_arr)  # Output: [1 2 3 99]
# append means add the element at last of the array

[1 2 3 4 5 6]
[ 1  2  3 99]


In [ ]:
import numpy as np
ar = np.array([2,3,4,5,6])
# copy function is use to copy the array
c = ar.copy()
c[0] = 12
# printing the values
print("Original array : ",ar)
print("assigned array : ",c)

Original array :  [2 3 4 5 6]
assigned array :  [12  3  4  5  6]


In [ ]:
# this is the program by which to array is add
import numpy as np
arr2 = np.array([2,3,4,5,6])
print("Original array : ",arr2)
# appending to the array
arr3 =np.array([7,8,9])
arr1 = np.append(arr2,arr3)
print("New array : ",arr1)

Original array :  [2 3 4 5 6]
New array :  [2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np
ar2= np.array([2,3,4,5,6])
#  view function provides a new way of looking at the same data without creating a copy.
cd = ar2.view()
cd[0] = 12
# printing the values
print("Original array : ",ar2)
print("assigned array : ",cd)

Original array :  [12  3  4  5  6]
assigned array :  [12  3  4  5  6]


In [ ]:
a = np.array([1,2,3])
a[1]=5
print(a)

[1 5 3]


In [ ]:
# here we access the every element of the array
arr = np.array([1,2,3])
for x in arr:
    print(x)

1
2
3


In [ ]:
from typing import Concatenate
import numpy as np

# Example using numpy.append
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result_append = np.append(arr1, arr2)
print(result_append) # Output: [1 2 3 4 5 6]

# Example using numpy.concatenate
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6], [7, 8]])
result_concat = np.concatenate((arr3, arr4), axis=1)
# concantenate function is use to join the array
print(result_concat)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]
#  know the main difference in append and Concatenate is

[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
from typing import Concatenate
import numpy as np

# Example using numpy.append
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result_append = np.append(arr1, arr2)
print(result_append) # Output: [1 2 3 4 5 6]

# Example using numpy.concatenate
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6], [7, 8]])
result_concat = np.concatenate((arr3, arr4),axis = 0)
print(result_concat)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]
#  know the main difference in append and Concatenate is

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# this loop works in one by one
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)
# here this loop in only works in on
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
  for y in x:
    print(y)

[1 2 3]
[4 5 6]
1
2
3
4
5
6
