In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,5,8])
# here where function is use to find the index of the element in the array
x=np.where(arr==5)
y=np.where(arr==50)
print(x)
print(y)

(array([4, 6]),)
(array([], dtype=int64),)


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,5,8])
x=np.where(arr%2==0)
print(x)
# here arr[x] prints the element of the array
print(arr[x])

(array([1, 3, 5, 7]),)
[2 4 6 8]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,5,8])
x=np.where(arr%2==0)
print(x)
print(arr[x])
# here len prints the length of the array
print(len(arr[x]))

(array([1, 3, 5, 7]),)
[2 4 6 8]
4


In [ ]:
import numpy as np
arr = np.array([1,22,3,45,58,6,5,88])
# np.sort sort the array in ascending order
print(np.sort(arr))

[ 1  3  5  6 22 45 58 88]


In [ ]:
import numpy as np

arr = np.array([1, 22, 3, 45, 58, 6, 5, 88])
sorted_desc = np.sort(arr)[::-1]  # Sort ascending, then reverse
print(sorted_desc)
print(arr)


[88 58 45 22  6  5  3  1]
[ 1 22  3 45 58  6  5 88]


In [ ]:
# this is the sorting of 2d array row wise
arr = np.array([[1, 22, 3, 45],[ 58, 6, 5, 88]])
print(np.sort(arr))
print("Shape:", arr.shape)

[[ 1  3 22 45]
 [ 5  6 58 88]]
Shape: (2, 4)


In [ ]:
arr = np.array([True,False,True])
print(np.sort(arr))


[False  True  True]


In [ ]:
arr=np.array([1,2,3,4,5,6,7])


In [ ]:
arr = np.array([[[1, 22, 3, 45],[ 58, 6, 5, 88]],[[2,1,5,6],[ 58, 6, 5, 88]]])
print(np.sort(arr))
sorted_desc = np.sort(arr)[::-1]  # Sort ascending, then reverse in three dimension
print(sorted_desc)
print("Shape:", arr.shape)

[[[ 1  2  5  6]
  [ 5  6 58 88]]

 [[ 1  3 22 45]
  [ 5  6 58 88]]]
Shape: (2, 2, 4)


In [ ]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
print(x1)
print(x2)
print(np.add(x1, x2))

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[2. 2. 2.]
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


In [ ]:
import numpy as np
# ones function prints the array of ones
n = np.ones(3)
print(n)
# here it print in 2 dimension one
o = np.ones((3, 3))
print(o)
n = 2*np.ones(3)
print(n)


[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[2. 2. 2.]


In [ ]:
import numpy as np

arr = np.array([[1, 22, 3, 45], [58, 6, 5, 88]])
sorted_arr = np.sort(arr, axis=0)  # Sorts column-wise
print(sorted_arr)


[[ 1  6  3 45]
 [58 22  5 88]]
