In [ ]:
import numpy as np
a=np.arange(0,6)
print(a)
# it sum the aray
a+a

[0 1 2 3 4 5]


array([ 0,  2,  4,  6,  8, 10])

In [ ]:
import numpy as np

a = np.arange(3, 6)   # [3, 4, 5]
b = np.arange(3, 6)   # [3, 4, 5]

# to do addition size of both array should be same
print(a)         # Output: [3 4 5]
print(b)         # Output: [3 4 5]
print(a + b)     # [6 8 10]
print(a - b)     # [0 0 0]
print(a * b)     # [9 16 25]
print(a / b)     # [1. 1. 1.]
print(a % b)     # [0 0 0]


[3 4 5]
[3 4 5]
[ 6  8 10]
[0 0 0]
[ 9 16 25]
[1. 1. 1.]
[0 0 0]


In [ ]:
a=np.arange(5)
a**a

array([  1,   1,   4,  27, 256])