In [ ]:
import numpy as np
a=np.array([[1,2,3],[2,3,4]])
print(a.ndim)
print(a.shape)
print(a)
# reshape changes the shape of array it depends on how many elements in a array
b=a.reshape(3,2)
print(b.ndim)
print(b.shape)
print(b)


2
(2, 3)
[[1 2 3]
 [2 3 4]]
2
(3, 2)
[[1 2]
 [3 2]
 [3 4]]


In [ ]:
a=np.array([[1,2,3],[2,3,4]])
b=a.reshape(1,6)
print(b)
c=np.arange(12)
print(c)
d = c.reshape(6,2)
print(d)
e =c.reshape(2,3,2)
print(e)
# in reshape if we use -1 then it will automatically convert the array into 1D array
f = c.reshape(-1)
print(f)


[[1 2 3 2 3 4]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
a=np.array([1,2,3,4])
# size prints the number of elements in array
print(a.size)
# itemsize prints the size of each element in array
print(a.itemsize)
# nbytes prints the total size of array
print(a.nbytes)
# dtype prints the size of datatype in array
print(a.dtype)

4
8
32
int64


In [ ]:
a = np.array([[1,4,7],[2,5,8],[5,7,8]])
# FLATTEN prints the element in 1 dim in row wise
b=a.flatten()
print(b)

[1 4 7 2 5 8 5 7 8]


In [ ]:
a = np.array([[1,4,7],[2,5,8],[5,7,8]])
# and when we use flatten('F') it prints the element in 1 dim in column wise
# in mysql there is no option of column wise so we use flatten('F')
# in flatten we use F to print column wise
b=a.flatten('F')
print(b)

[1 2 5 4 5 7 7 8 8]
