In [2]:
import numpy as np
a=np.arange(10)
print(a)
# arange function creates an array of evenly spaced values within a given interval
# The function takes three arguments: start, stop, and step
b = a[2:7:2]
print(b)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[::-1])
print(arr[2::-1])
print(arr[:2:-1])
print(arr[5:3:-1])

[7 6 5 4 3 2 1]
[3 2 1]
[7 6 5 4]
[6 5]


In [3]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:6:2])
print(arr[::2])
print(arr[::])
print(arr[::-2])
print(arr[4::4])
print(arr[1:1:1])

[2 4 6]
[1 3 5 7]
[1 2 3 4 5 6 7]
[7 5 3 1]
[5]
[]


In [4]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[4:6:-1])

[]


In [5]:
arr = np.array([[1,2,3,5,4],[3,4,5,6,7],[3,4,5,4,7]])

print(arr[1,1:4])
print(arr[1:])
print(arr[1:2,::-1])
print("hlo")
arr = np.array([[1,2,3,5,4],[3,4,5,6,7]])
print(arr[0:,:4])
print("hlo")
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2:2,1:4:2])
print("hlo")
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[4 5 6]
[[3 4 5 6 7]
 [3 4 5 4 7]]
[[7 6 5 4 3]]
hlo
[[1 2 3 5]
 [3 4 5 6]]
hlo
[[2 4]]
hlo
[[2 3 4]
 [7 8 9]]


In [ ]:
arr = np.array([[[1,2,3,5],[3,4,5,67]],[[3,4,5,4],[3,4,5,6]]])
print(arr[1,1,1])
print(arr[::1,1,1])
print(arr[::2,1,1])
print(arr[::,::,1])
print("br")
print(arr[::,::,:2:1])

4
[4 4]
[4]
[[2 4]
 [4 4]]
br
[[[1 2]
  [3 4]]

 [[3 4]
  [3 4]]]
